/**
 * RichTextEditor — Inline Quill WYSIWYG editor for Grist cells.
 *
 * Opens as a popup over the cell when editing a "RichText" widget.
 * Supports: bold, italic, superscript, subscript.
 * Enter saves, Shift+Enter for newline, Escape cancels, Tab/Shift+Tab navigates.
 *
 * KEY DESIGN DECISIONS:
 *
 * 1. We do NOT use commandGroup.attach() because it's a dom.inlinable designed
 *    for DOM builders (dom("textarea", commandGroup.attach())), not for attaching
 *    to Quill's dynamically-created contenteditable div.
 *
 * 2. We do NOT stopPropagation for regular keys. Mousetrap's built-in stopCallback
 *    already checks element.isContentEditable and skips shortcuts for contenteditable
 *    elements. Stopping propagation in capture phase would prevent keydown from reaching
 *    child elements (<p>, <span>) inside .ql-editor, breaking text input.
 *
 * 3. We only intercept Enter/Escape/Tab in capture phase with stopImmediatePropagation
 *    to handle them before Quill or Grist can process them.
 *
 * 4. Quill CSS is loaded via <link> tag because the Snow theme SVG toolbar icons
 *    are generated by Quill's JS and need the full theme CSS.
 */

import {createGroup} from 'app/client/components/commands';
import {testId} from 'app/client/ui2018/cssVars';
import {getButtonMargins} from 'app/client/widgets/EditorButtons';
import {EditorPlacement} from 'app/client/widgets/EditorPlacement';
import {FieldOptions, NewBaseEditor} from 'app/client/widgets/NewBaseEditor';
import {CellValue} from 'app/common/DocActions';
import {undef} from 'app/common/gutil';
import {dom, Observable, styled} from 'grainjs';

const Mousetrap = require('app/client/lib/Mousetrap');
const QuillModule = require('quill');
const Quill = QuillModule.default || QuillModule;

// ─── Quill CSS ─────────────────────────────────────────────────────────────
// For offline/self-hosted: copy node_modules/quill/dist/quill.snow.css to
// grist-core/static/quill.snow.css and change this to '/quill.snow.css'
const QUILL_CSS_URL = 'https://cdn.jsdelivr.net/npm/quill@1.3.7/dist/quill.snow.css';

function ensureQuillCss() {
  if (document.getElementById('grist-quill-css')) { return; }
  const link = document.createElement('link');
  link.id = 'grist-quill-css';
  link.rel = 'stylesheet';
  link.href = QUILL_CSS_URL;
  document.head.appendChild(link);

  // Grist-specific overrides
  const style = document.createElement('style');
  style.id = 'grist-quill-overrides';
  style.textContent = `
    .grist-richtext-editor .ql-toolbar.ql-snow {
      border: none;
      border-bottom: 1px solid #e0e0e0;
      padding: 4px 8px;
      background: #fafafa;
    }
    .grist-richtext-editor .ql-container.ql-snow {
      border: none;
      font-family: inherit;
      font-size: 13px;
    }
    .grist-richtext-editor .ql-editor {
      padding: 6px 10px;
      min-height: 40px;
      max-height: 300px;
      overflow-y: auto;
    }
    .grist-richtext-editor .ql-editor p {
      margin: 0;
    }
    .grist-richtext-editor .ql-snow .ql-active .ql-stroke {
      stroke: #16b378;
    }
    .grist-richtext-editor .ql-snow .ql-active .ql-fill {
      fill: #16b378;
    }
    .grist-richtext-editor .ql-snow .ql-active {
      color: #16b378;
    }
  `;
  document.head.appendChild(style);
}


export class RichTextEditor extends NewBaseEditor {
  // Required by Grist's draft/undo system
  public readonly editorState: Observable<string>;

  private _quill: any;
  private _container: HTMLElement;
  private _editorPlacement!: EditorPlacement;
  private _dom: HTMLElement;

  constructor(options: FieldOptions) {
    super(options);
    ensureQuillCss();

    const initialValue: string = undef(
      options.state as string | undefined,
      options.editValue,
      String(options.cellValue ?? '')
    );

    this.editorState = Observable.create<string>(this, initialValue);

    // Activate the command group so Grist knows these commands have an active
    // implementation (fieldEditSave, fieldEditCancel, prevField, nextField, etc.)
    // We do NOT call .attach() — see file header for why.
    this.autoDispose(createGroup(options.commands, this, true));

    this._dom = cssRichEditorWrap(
      testId('widget-richtext-editor'),
      // CRITICAL: stop mousedown from reaching the Grist grid.
      // Without this, clicking in the editor deselects the cell,
      // focus returns to clipboard, clipboard_focus fires, editor closes.
      dom.on('mousedown', (e: MouseEvent) => e.stopPropagation()),
      this._container = cssQuillContainer(),
    );
    // Add the CSS class for our style overrides
    this._dom.classList.add('grist-richtext-editor');
  }

  public attach(cellElem: Element): void {
    // Position the editor popup over the cell
    this._editorPlacement = EditorPlacement.create(this, this._dom, cellElem, {
      margins: getButtonMargins(),
    });
    this.autoDispose(
      this._editorPlacement.onReposition.addListener(() => this._resize(), this)
    );

    // Initialize Quill with limited toolbar
    this._quill = new Quill(this._container, {
      theme: 'snow',
      modules: {
        toolbar: [
          ['bold', 'italic'],
          [{'script': 'super'}, {'script': 'sub'}],
          ['clean'],
        ],
        keyboard: {
          bindings: {
            // Override Quill's default Enter: don't insert newline.
            // Our keydown handler below will trigger save instead.
            enter: {
              key: 13,
              handler: () => false,
            },
            // Shift+Enter: let Quill insert a newline
            shiftEnter: {
              key: 13,
              shiftKey: true,
              handler: () => true,
            },
          },
        },
      },
    });

    // ── Keyboard handling ──────────────────────────────────────────────
    //
    // Only intercept the 3 keys that need special handling.
    // All other keys propagate normally — Mousetrap's built-in stopCallback
    // detects isContentEditable and won't process shortcuts, so Quill
    // receives all keystrokes without interference.
    //
    const qlEditor = this._container.querySelector('.ql-editor') as HTMLElement;

    if (qlEditor) {
      // Block Mousetrap for any combos that might slip through
      // (e.g. alwaysOn shortcuts). Returns true = "stop, don't process".
      Mousetrap.setCustomStopCallback(qlEditor, () => true);

      const keyHandler = (e: KeyboardEvent) => {
        if (e.key === 'Enter' && !e.shiftKey) {
          e.preventDefault();
          e.stopImmediatePropagation();
          this.options.commands.fieldEditSaveHere();
          return;
        }

        if (e.key === 'Escape') {
          e.preventDefault();
          e.stopImmediatePropagation();
          this.options.commands.fieldEditCancel();
          return;
        }

        if (e.key === 'Tab') {
          e.preventDefault();
          e.stopImmediatePropagation();
          if (e.shiftKey) {
            this.options.commands.prevField?.();
          } else {
            this.options.commands.nextField?.();
          }
          return;
        }

        // ALL OTHER KEYS: do nothing. Let them propagate naturally.
        // - Browser handles text input in contenteditable natively
        // - Quill's keyboard module processes its own bindings
        // - Mousetrap's stopCallback sees isContentEditable=true and
        //   skips shortcut processing
      };

      // Use capture phase so we get Enter/Escape/Tab before Quill
      qlEditor.addEventListener('keydown', keyHandler, true);
      this.onDispose(() => qlEditor.removeEventListener('keydown', keyHandler, true));
    }

    // Block Mousetrap on toolbar too (clicking bold/italic etc.)
    const toolbar = this._container.querySelector('.ql-toolbar') as HTMLElement;
    if (toolbar) {
      Mousetrap.setCustomStopCallback(toolbar, () => true);
    }

    // Track changes for Grist's draft system
    this._quill.on('text-change', (_delta: any, _oldDelta: any, source: string) => {
      if (source === 'user') {
        this.editorState.set(this._getHtml());
        this._resize();
      }
    });

    // Load existing value
    const value = String(this.options.editValue ?? this.options.cellValue ?? '');
    if (value) {
      this._quill.clipboard.dangerouslyPasteHTML(value);
    }

    this._resize();

    // Focus after Grist's own focus management (FloatingEditor, clipboard) finishes
    setTimeout(() => {
      if (!this.isDisposed()) {
        this._quill.focus();
        const length = this._quill.getLength();
        this._quill.setSelection(Math.max(0, length - 1), 0);
      }
    }, 0);
  }

  public getDom(): HTMLElement {
    return this._dom;
  }

  public getCellValue(): CellValue {
    return this._getHtml();
  }

  public getTextValue(): string {
    return this._quill?.getText() || '';
  }

  public getCursorPos(): number {
    const sel = this._quill?.getSelection();
    return sel ? sel.index : 0;
  }

  private _getHtml(): string {
    if (!this._quill) { return ''; }
    const html = this._container.querySelector('.ql-editor')?.innerHTML || '';
    return html === '<p><br></p>' ? '' : html;
  }

  private _resize() {
    if (!this._editorPlacement) { return; }
    const toolbarEl = this._container.querySelector('.ql-toolbar') as HTMLElement;
    const editorEl = this._container.querySelector('.ql-editor') as HTMLElement;
    const toolbarH = toolbarEl?.offsetHeight || 36;
    const editorH = editorEl?.scrollHeight || 40;
    this._editorPlacement.calcSize({
      width: Math.max(280, this._container.scrollWidth),
      height: Math.max(100, toolbarH + editorH + 12),
    });
  }
}

const cssRichEditorWrap = styled('div', `
  display: flex;
  flex-direction: column;
  background: white;
  border: 1px solid #a9a9a9;
  border-radius: 3px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  min-width: 280px;
  overflow: hidden;
  z-index: 100;
`);

const cssQuillContainer = styled('div', `
  min-height: 60px;
`);